version: '2'
services:
  db:
    image: mysql
    volumes:
      - "/tmp/.data/db:/var/lib/mysql"
      - ./src/main/mysql/data.sql:/tmp/data.sql
      - ./src/main/mysql/init.sh:/tmp/entry.sh
      - ./src/main/mysql/my.cnf:/etc/mysql/my.cnf
      - ./src/main/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_SCRIPT: '/tmp/data.sql'
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    command: /tmp/entry.sh